@mysql_db_name = 'item_template'
@structName = 'Item'

@struct = [
	[:int, :entry],
	[:int, :class],
	[:int, :subclass],
	[:string, :name],
	[:int, :displayid],
	[:int, :quality],
	[:int, :flags],
	[:int, :flagsExtra],
	[:int, :buyCount],
	[:int, :buyPrice],
	[:int, :sellPrice],
	[:int, :inventoryType],
	[:int, :allowableClass],
	[:int, :allowableRace],
	[:int, :itemLevel],
	[:int, :requiredLevel],
	[:int, :requiredSkill],
	[:int, :requiredSkillRank],
	[:int, :maxCount],
	[:int, :stackable],
	[:int, :containerSlots],
	[:int, :statsCount],
] + sql_pair(:int, [:stat_type, :stat_value], 10) +
sql_pair(:float, [:dmg_min, :dmg_max], 2) +
sql_pair(:int, [:dmg_type], 2) + [
	[:int, :armor],
	[:int, :holy_res],
	[:int, :fire_res],
	[:int, :nature_res],
	[:int, :frost_res],
	[:int, :shadow_res],
	[:int, :arcane_res],
	[:int, :delay],
	[:int, :ammo_type],
	[:int, :bonding],
	[:string, :description],
	[:int, :startQuest],
	[:int, :lockId],
	[:int, :material],
	[:int, :sheath],
	[:int, :randomProperty],
	[:int, :randomSuffix],
	[:int, :block],
	[:int, :itemset],
	[:int, :maxDurability],
	[:int, :bagFamily],
	[:int, :totemCategory],
	[:int, :requiredDisenchantSkill],
	[:int, :duration],
	[:int, :disenchantId],
	[:int, :foodType],
	[:int, :minMoneyLoot],
	[:int, :maxMoneyLoot],
]
