@mysql_db_name = 'item_template'
@structName = 'Item'

@struct = [
c(:int, :entry),
c(:int, :class),
c(:int, :subclass),
c(:string, :name),
c(:int, :displayId),
c(:int, :quality),
c(:int, :flags),
c(:int, :flagsExtra),
c(:int, :buyCount),
c(:int, :buyPrice),
c(:int, :sellPrice),
c(:int, :inventoryType),
c(:int, :allowableClass),
c(:int, :allowableRace),
c(:int, :itemLevel),
c(:int, :requiredLevel),
c(:int, :requiredSkill),
c(:int, :requiredSkillRank),
c(:int, :maxCount),
c(:int, :stackable),
c(:int, :containerSlots),
c(:int, :statsCount),
mc(:int, [:stat_type, :stat_value], 10),
mc(:float, [:dmg_min, :dmg_max], 2),
mc(:int, [:dmg_type], 2),
c(:int, :armor),
c(:int, :holy_res),
c(:int, :fire_res),
c(:int, :nature_res),
c(:int, :frost_res),
c(:int, :shadow_res),
c(:int, :arcane_res),
c(:int, :delay),
c(:int, :ammo_type),
c(:int, :bonding),
c(:string, :description),
c(:int, :startQuest),
c(:int, :lockId),
c(:int, :material),
c(:int, :sheath),
c(:int, :randomProperty),
c(:int, :randomSuffix),
c(:int, :block),
c(:int, :itemset),
c(:int, :maxDurability),
c(:int, :bagFamily),
c(:int, :totemCategory),
c(:int, :requiredDisenchantSkill),
c(:int, :duration),
c(:int, :disenchantId),
c(:int, :foodType),
c(:int, :minMoneyLoot),
c(:int, :maxMoneyLoot),
mc(:int, [:spellId, :spellTrigger, :spellCharges, :spellCooldown,
	:spellCategory, :spellCategoryCooldown], 5, '_'),
mc(:float, [:spellPpmRate], 5, '_'),
]

@index = [
[:spellId],
[:displayId],
]
