require "#{File.dirname(__FILE__)}/arg_handler.rb"

Works.registerArgHandler('CONFIG') do |value|
	CCompileWork.setConfig(value)
end

require "#{File.dirname(__FILE__)}/work.rb"
#require "#{File.dirname(__FILE__)}/config.rb"
require "#{File.dirname(__FILE__)}/flags.rb"
require 'fileutils'

# Base class for compiling C/C++/Objective-C files.
# FileTask.name is the name of the object file.
# The source file and any headers it might include are prerequisites.

# This class does not specify the use of any particular compiler, like GCC, LLVM, QCC or MSVC.
# Such information is included from a module whose name is an argument to CppTask.initialize.

# The default compiler is specified in config.rb, which may be locally overridden by local_config.rb.

class CCompileTask < FileTask
	include FlagsChanged

	def initialize(srcTask, flags, builddir, requirements, compilerModule = DefaultCCompilerModule)
		@compilerModule = compilerModule
		extend compilerModule

		@SOURCE = srcTask
		@DEPFILE = CCompileTask.genFilename(builddir, srcTask, '.mf')
		@NAME = CCompileTask.genFilename(builddir, srcTask, objFileEnding)
		@FLAGS = flags

		#p srcTask, requirements

		@requirements = requirements

		@prerequisites = [
			srcTask,
			DirTask.new(builddir),
		]

		# Only if the file is not already needed do we care about extra dependencies.
		setNeeded
		if(!needed)
			@prerequisites += loadDependencies
		end

		super(@NAME)
	end

	def cFlags
		return @cFlags if(@cFlags)
		return @cFlags = compileCmd
	end

	def fileExecute
		execFlags
		sh cFlags
		postCompile
	end

	# Returns a path representing a generated file, given a source filename and a new file ending.
	def self.genFilename(builddir, source, ending)
		builddir + File.basename(source.to_s).ext(ending)
	end
end


# Base class for compiling multiple C-type files into a single unit.
# For example, an exe, dll or lib file.

# Subclasses MUST implement the following methods:
# targetName() -> String	# Returns name of target file.

# Instances MUST set one or more of the following variables:
# @SOURCES, @SOURCE_FILES, @SOURCE_TASKS or @EXTRA_OBJECTS.

# Instances MUST set ALL the following variables:
# @NAME
## String, base name of the target.
## Example: in an ExeWork, if @NAME == 'foo', target becomes @BUILDDIR/foo.exe.

# Instances MAY provide the other variables found in set_defaults.

class CCompileWork < FileTask
	include FlagsChanged

	def self.setConfig(value)
		@@CONFIG = value
	end

	def set_defaults
		# Array of Strings, directories that will be searched for source files.
		default(:SOURCES, [])
		# Array of Strings, paths to files that should be compiled, even though they are outside the SOURCES.
		default(:SOURCE_FILES, [])
		# Array of FileTasks, generated source files that should be compiled along with the others.
		default(:SOURCE_TASKS, [])

		# Array of Strings, names of files that should not be compiled.
		# Applies only to files found by @SOURCES.
		default(:IGNORED_FILES, [])
		# Array of FileTasks, precompiled object files, to link with.
		default(:EXTRA_OBJECTS, [])

		# String, extra flags used when compiling C files.
		default(:EXTRA_CFLAGS, '')
		# String, extra flags used when compiling C++ files.
		default(:EXTRA_CPPFLAGS, '')
		# Array of Strings, extra include directories.
		default(:EXTRA_INCLUDES, [])
		# String, extra flags passed to the linker.
		default(:EXTRA_LINKFLAGS, '')

		# Array of FileTasks, static libraries to link with.
		default(:LOCAL_LIBS, [])
		# Array of FileTasks, shared libraries to link with.
		default(:LOCAL_DLLS, [])
		# Array of Strings, names of libraries to link with.
		default(:LIBRARIES, [])

		# Hash(String,String). Key is the filename of a source file.
		# Value is extra compile flags to be used when compiling that file.
		default(:SPECIFIC_CFLAGS, {})

		# Boolean. While true, assembly source files will be automatically collected
		# from SOURCE directories, much like C/C++ files.
		default(:COLLECT_S_FILES, true)

		# String. 'release' or 'debug'.
		default(:CONFIG, 'release')

		# String, name of the base build directory.
		default(:BUILDDIR_BASE, 'build/')
		# String, added to the beginning of build sub-directories.
		default(:BUILDDIR_PREFIX, '')
		# String, name of the build sub-directory.
		default(:BUILDDIR_NAME, @BUILDDIR_PREFIX + @CONFIG + builddir_postfix)
		# String, path of the build directory.
		default(:BUILDDIR, @BUILDDIR_BASE + @BUILDDIR_NAME + '/')

		# Array of Tasks, requirements for all CCompileTasks generated by this Work
		default(:REQUIREMENTS, [])

		default(:prerequisites, [])
	end

	def initialize(compilerModule = DefaultCCompilerModule, &block)
		@compilerModule = compilerModule
		extend compilerModule

		@CONFIG = @@CONFIG if(defined?(@@CONFIG))

		instance_eval(&block) if(block)

		if(!(@SOURCES || @SOURCE_FILES || @SOURCE_TASKS || @EXTRA_OBJECTS))
			raise 'Need @SOURCES, @SOURCE_FILES, @SOURCE_TASKS or @EXTRA_OBJECTS'
		end

		need(:@NAME)

		set_defaults

		# find source files
		cfiles = collect_source_files('.c')
		@cppfiles = collect_source_files('.cpp') + collect_source_files('.cc') + collect_source_files('.C')

		sfiles = []
		if(@COLLECT_S_FILES)
			sfiles = collect_source_files('.s')
		end

		all_sourcefiles = cfiles + @cppfiles + sfiles

		loadCommonFlags

		@object_tasks = collect_objects(all_sourcefiles) + @EXTRA_OBJECTS + @LOCAL_LIBS + @LOCAL_DLLS
		@prerequisites += @object_tasks

		super(File.expand_path(targetName()))
	end

	def cFlags
		return @cFlags if(@cFlags)
		return @cFlags = linkCmd
	end

	def fileExecute
		execFlags
		sh cFlags
		postLink
	end

private

	def check_extra_sourcefile(file, ending)
		return false if(file.getExt != ending)
		raise "Extra sourcefile '#{file}' does not exist!" if(!File.exist?(file))
		return true
	end

	# returns an array of source-code FileTasks
	def collect_source_files(ending)
		files = @SOURCES.collect {|dir| Dir[dir+'/*'+ending]}
		files.flatten!
		files.reject! {|file| @IGNORED_FILES.member?(File.basename(file)) ||
			!file.end_with?(ending)}	# this one's for windows, whose Dir[] implementation is not case-sensitive.
		files += @SOURCE_FILES.select do |file| check_extra_sourcefile(file, ending) end
		tasks = files.collect do |file| FileTask.new(file) end
		extra_tasks = @SOURCE_TASKS.select do |file| file.to_s.getExt == ending end
		# todo: make sure all sourcetasks are collected by one of the calls to this function.
		return extra_tasks + tasks
	end

	def getFlags(source)
		need(:@SPECIFIC_CFLAGS)
		ext = source.to_s.getExt
		flags = @CFLAGS_MAP[ext]
		if(flags == nil) then
			error "Bad ext: '#{ext}' on source '#{source}'"
		end
		return flags + @SPECIFIC_CFLAGS.fetch(File.basename(source.to_s), "")
	end

	# returns an array of CCompileTasks
	def collect_objects(sources)
		return sources.collect do |s| CCompileTask.new(s, getFlags(s), @BUILDDIR, @REQUIREMENTS, @compilerModule) end
	end
end
